# Sample Pipeline showing a continuous build for Static Website
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'site-contents'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/site'
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/site'
      ArtifactName: 'site'
      publishLocation: 'Container'