# This is a basic workflow to help you get started with Actions

name: Upload Static Website to Blob Storage

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths: site-contents/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STATICSITE_CREDENTIALS }}
          
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name azcdnstgacct -d '$web' -s .
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name cdn-profile-azcdn --name azcdncdnendpoint --resource-group azcdn-rg
            
    # Logout of Azure
      - name: logout
        run:  |
          az logout
