# This is a basic workflow to help you get started with Actions

name: Upload Static Website to Blob Storage

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths: 
    - 'site-contents/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_STATICSITE_CREDENTIALS }}
          
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.STATICSITE_STGACCT }} -d '$web' -s ${{ secrets.STATICSITE_SOURCE }}
      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az cdn endpoint purge --content-paths "/*" --profile-name ${{ secrets.CDN_PROFILE_NAME }} --name ${{ secrets.CDN_ENDPOINT_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
            
    # Logout of Azure
      - name: logout
        run:  |
          az logout
